WasteOil2/urls.py
from unicodedata import name
from django import urls
from django.contrib import admin
from django.urls import path,include
from oil import views



#Main Url File


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name = "index"),
    path('oils/',include("oil.urls")),
    path('user/',include("user.urls"))
]

oil/urls.py
from django.contrib import admin
from django.urls import path
from oil import views

app_name = "oil"

urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('about/',views.about,name="about"),
    path('addoil/',views.addOil,name="addoil"),
    path('update/<int:id>',views.updateOil,name="update"),
    path('delete/<int:id>',views.deleteOil,name="delete")
]

user/urls.py
from django.contrib import admin
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path('register/',views.register2,name="register2"),
    path('login/',views.login2,name="login2"),
    path('logout/',views.logout2,name="logout2"),
    #path('logout/',views.logoutUser,name="logout")
]

oil/models.py
from ensurepip import version
from django.db import models

# Create your models here.

class Oil(models.Model): # Modelimizi oluşturduk.
    user = models.ForeignKey("auth.User",on_delete=models.PROTECT,verbose_name="Kullanıcı") 
    liter = models.DecimalField(max_digits=6,decimal_places=2,verbose_name="Litre")
    comp = models.CharField(max_length=50,verbose_name="Alınan Şirket")
    price = models.DecimalField(max_digits=6,decimal_places=2,verbose_name="Fiyat")
    date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi") 
    def __str__(self):
        return self.comp 

user/models.py
from django.db import models

# Create your models here.

oil/forms.py
from django import forms
from .models import Oil
#Yağları ekleyeceğimiz form alanı
#https://docs.djangoproject.com/en/3.2/topics/forms/modelforms/

class OilForm(forms.ModelForm):
    class Meta:
        model = Oil #Formumuz ile Oil modelimiz bağlamış olduk.
        fields = ['liter','comp','price']

user/forms.py
from cProfile import label
from enum import unique
from cv2 import convertPointsFromHomogeneous
from django import forms

#RegisterForm Model

class RegisterForm(forms.Form):

    username = forms.CharField(max_length=50,label="Kullanıcı Adı")
    password = forms.CharField(max_length=20,label="Parola",widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label="Parola",widget=forms.PasswordInput)
    

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar eşleşmiyor")
        
        values = {
            "username" : username,
            "password" : password
        }

        return values

oil/views.py
import re
from unicodedata import name
from django.shortcuts import get_object_or_404, redirect, render,HttpResponse
from django.contrib import messages
from .models import Oil
from oil.models import Oil
from .forms import OilForm
from django.contrib.auth.decorators import login_required #for login required decorator

# Create your views here.

@login_required(login_url='user:login2')
def index(request):
    return render(request,"index.html")
    
def about(request):
    return render(request,"about.html")

def dashboard(request):
    oils = Oil.objects.filter(user = request.user)
    context = {
        "oils":oils
    }
    return render(request,"dashboard.html",context)

def addOil(request):
    form = OilForm(request.POST or None) #form objemizi oluşturduk. Post request olursa formumuz post requestten gelen bilgilerle doldurulacak.
    if form.is_valid():
        oil = form.save(commit=False) #Bizim modelimizde user özelliği olduğu için bunu belirtmemiz lazım false diyerek bunu kendimizin belirteceğini söyledik. 
        oil.user = request.user
        oil.save()
        messages.success(request,"Kayıt başarılı bir şekilde oluşturuldu")
        return redirect("index")
    return render(request,"addoil.html",{"form":form})

def updateOil(request,id):
    oil = get_object_or_404(Oil,id = id)
    form = OilForm(request.POST or None,instance=oil) #İnstance gelen bilgileri yeni forma aktardık
    if form.is_valid():
        oil = form.save(commit=False)
        oil.user = request.user
        oil.save()
        messages.success(request,"Güncelleme başarılı")
        return redirect("oil:dashboard")
    return render(request,"update.html",{"form":form})

def deleteOil(request,id):
    return render(request,"delete.html")
    

user/views.py
import imp
from multiprocessing import context
from operator import index
from cv2 import RQDecomp3x3
from django.contrib import messages
from django.shortcuts import redirect, render
from django.template import RequestContext
from user import views
import user
from .forms import RegisterForm #Register formumuzu dahil ettik

from django.contrib import messages

from django.contrib.auth.decorators import login_required #for login required decorator

from .models import *

from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm


# Create your views here.

def register(request):
    
    form = RegisterForm(request.POST or None) #Formumuzu Register formdan gelen bilgilerle doldurduk.
    if form.is_valid():
        username = form.cleaned_data.get("username") #Clean methodundan dönen değerlerimizi burada aldık
        password  = form.cleaned_data.get("password") 

        newUser = User(username = username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        messages.success(request,"Başarı ile kayıt oldunuz. Giriş Yaptıldı !")

        return redirect("index")
        
    context={
            "form":form
        }
    return render(request,"register.html",context)
    
        
    """form = RegisterForm()
    context= {
        "form" : form
    }"""

def register2(request):
    if request.user.is_authenticated:
        return redirect('index')
    else:
        form = UserCreationForm() 
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                messages.success(request,"Başarı ile kayıt oldunuz")
                
                return redirect('user:login2')
    
    context = {
        "form" : form
    }
    return render(request,"register2.html",context)


def login2(request):

    if request.method == 'POST':
        
        username = request.POST.get('username') #formdaki username bilgisini aldık
        password = request.POST.get('password') #formdaki password bilgisini aldık

        user = authenticate(request, username=username , password=password) #authenticate işlemi

        if user is not None: #Yukarıdaki değerler sağlandıysa
            login(request, user)
            return redirect('index')
        else:
            messages.error(request,'Kullanıcı adı veya parola yanlış')

    context={}
    return render(request,"login2.html",context)

def logout2(request):
    logout(request)
    return redirect('user:login2')

def loginUser(request):
    return render(request,"index.html")

def logoutUser(request):
    return render(request,"index.html")

templates/about.html
{% extends 'layout.html' %}


{% block body %}
<div class="px-4 pt-5 my-5 text-center border-bottom">
    <h1 class="display-4 fw-bold">Centered screenshot</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
        <button type="button" class="btn btn-primary btn-lg px-4 me-sm-3">Primary button</button>
        <button type="button" class="btn btn-outline-secondary btn-lg px-4">Secondary</button>
      </div>
    </div>
    <div class="overflow-hidden" style="max-height: 40vh;">
      <div class="container px-5">
        <img src="/static/png/starbucks.png" class="img-fluid border rounded-3 shadow-lg mb-4" alt="Example image" width="700" height="500" loading="lazy">
      </div>
    </div>
  </div>
{% endblock body %} 

templates/addoil.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %} <!--Crispy Formu dahil ettik-->

{% block body %}

<div class="container">
    <h1 class="display-3">Kayıt Ekleyin</h1>
    <div class="row">
        <div style="margin: 30px; padding: 20px;"class="col-6 col-sm-3">
            <h3 class="">Kayıt Girişi</h3>
            <form method="post">
                {% csrf_token %}

                {{form|crispy}} <!--Formumuzu ekledik-->
                <hr>
                <button type="submit" class="btn btn-outline-danger btn-md">Oluştur</button>
            </form>
            
        </div>
    </div>
</div>

{% endblock body %}

templates/dashboard.html
{% extends 'layout.html' %}

{% block body %} 
<div class="container">
    <h1 class="display-3">Kayıt Giriş</h1>
    <a style="margin-top:10px;" href="/oils/addoil" class="btn btn-danger">Kayıt Ekle</a>
    {% if oils %} <!-- Herhangi bir yağ girişi gönderilmişse -->
    <table style="margin-top: 60px;"class="table">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Litre</th>
          <th scope="col">Ekleyen</th>
          <th scope="col">Alınan</th>
          <th scope="col">Fiyat</th>
          <th scope="col">Tarih</th>
          <th scope="col">Güncelle</th>
          <th scope="col">Sil</th>
        </tr>
      </thead>
      <tbody>
           {% for oil in oils %}
           <tr>
              <th scope="row">{{oil.id}}</th>
              <td>{{oil.liter}}</td>
              <td>{{oil.user}}</td>
              <td>{{oil.comp}}</td>
              <td>{{oil.price}}</td>
              <td>{{oil.date}}</td>
              <td><a href="/oils/update/{{oil.id}}" class="btn btn-success">Güncelle</a></td>
              <td><a href="/oils/delete/{{oil.id}}" class="btn btn-danger">Sil</a></td>
            </tr>
           {% endfor %}
      </tbody>
    </table>
    {% else %}
    <div style="margin-top: 20px;"class="alert alert-danger">
      Henüz bir yağ girişi yok.
    </div>
    {% endif %}
    
</div>




{% endblock body %} 

templates/includes/messages.html
<div style="margin-top : 60px;"class="container-fluid">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </ul>
    {% endif %}
</div>

templates/includes/navbar.html
<style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
  .navbar-custom{
    background-color:lightseagreen;
  }
</style>

<nav class="navbar navbar-custom navbar-expand-md navbar-dark">
    <div class="container-md">
      <a class="navbar-brand" href="/">HAY Atık Yağ</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="/about">Hakkımızda</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/oils/addoil">Kayıt Ekle</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/oils/dashboard">Yağlar</a>
          </li>
        </ul>
      </div>
    </div>
    <div>
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <span class="hello-msg">Hello, {{request.user}}</span>
        </li>
        <li class="nav-item">
          <span><a href="{% url 'user:logout2' %}">Çıkış Yap</a></span>
        </li>
      </ul>
      
      
    </div>
    

  </nav>


  <!--  Search Form
      <form class="d-flex">
          <input class="form-control me-2" type="text" placeholder="Search">
          <button class="btn btn-primary" type="button">Search</button>
        </form>
  -->

templates/includes/sidebar.html
<style>
    
    .sidebar-custom{
      background-color:darkcyan;
    }
  </style>

<div class="d-flex flex-column vh-100 h-auto flex-shrink-0 p-3 text-white sidebar-custom" style="width: 250px;"> <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none"> <svg class="bi me-2" width="18" height="32"> </svg> <h4 class="display">HAY Waste Oil</h4> </a>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item"> <a href="" class="nav-link active" aria-current="page"> <i class="fa fa-home"></i><span class="ms-2">Başlangıç</span> </a> </li>
      <li> <a href="#" class="nav-link text-white"> <i class="fa fa-dashboard"></i><span class="ms-2">Hakkımızda</span> </a> </li>
      <li> <a href="{% url 'oil:dashboard' %}" class="nav-link text-white"> <i class="fa fa-first-order"></i><span class="ms-2">Alınanlar</span> </a> </li>
      <li> <a href="#" class="nav-link text-white"> <i class="fa fa-cog"></i><span class="ms-2">Satışar</span> </a> </li>
      <li> <a href="#" class="nav-link text-white"> <i class="fa fa-bookmark"></i><span class="ms-2">Ayarlar</span> </a> </li>
  </ul>
  <hr>
  <!-- Sidebar Dropdown -->
  <!-- <div class="dropdown"> <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false"> <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2"> <strong> John W </strong> </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
          <li><a class="dropdown-item" href="#">New project</a></li>
          <li><a class="dropdown-item" href="#">Settings</a></li>
          <li><a class="dropdown-item" href="#">Profile</a></li>
          <li>
              <hr class="dropdown-divider">
          </li>
          <li><a class="dropdown-item" href="#">Sign out</a></li>
      </ul>
  </div> -->
</div>

templates/includes/sidebar2.html
{% block body %}

{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class="container">
    <h1 class="display-3">Welcome to main page</h1>
    <h1 class="display-6">Let's get started</h1>
    <p class="lead">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempore placeat quisquaTempore placeat quisquaTempore placeat quisquaTempore placeat quisquaTempore placeat quisquaTempore placeat quisquaTempore placeat quisquam distinctio dolores cum est, mollitia eum in nulla sapiente consequatur, ipsam eaque nisi dignissimos dolor, molestias ratione doloribus laboriosam?</p>
    <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt vero dolorum culpa voluptates perferendis hic officia. Ex modi repudiandae quod earum dolore reprehenderit eos voluptatibus aperiam in asperiores. Tempora, ut.</p>
    <p class="lead text-end"> Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
    <button class="btn btn-outline-secondary btn-lg ">large outlined secondary</button>
    <button class="btn btn-outline-danger btn-lg">large outlined secondary</button>
</div>




{% endblock body %}

templates/layout.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <title>WasteOil</title>
    <style>
        .my-container{
           border: 1px solid green; 
        }
    </style>
</head>
<body>
    {% include "includes/navbar.html" %}
    
    {% comment %} {% include "includes/sidebar.html" %} {% endcomment %}
    
    {% include "includes/messages.html" %}

    
    
    
    {% block body %}
        
    {% endblock body %}


    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0/jquery-3.6.0.js' %}"></script>
    
</body>
</html>

templates/login.html
{% extends 'layout.html' %}

templates/login2.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #CD5C5C !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #F5B7B1;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 20px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 30px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">GİRİŞ YAP</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Kullanıcı Adı..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Parola..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
                
                {% for message in messages %}
                    <p id="messages">{{ message }}</p>
                {% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Hesabınız yok mu? <a href="{% url 'user:register2' %}" class="ml-2">Kayıt Ol</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

templates/register.html
{% extends 'layout.html' %}


{% block body %}
  <form method="post">
    
    <div class="mb-3">
      <h1 class="display-4 fw-bold text-center container-fluid">Kayıt Olun</h1>
      {% csrf_token %} 
      {{form.as_p}}
      <button type="submit" class="btn btn-danger">Kayıt Ol</button>
  </form>
{% endblock  %}

templates/register2.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #CD5C5C !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #F5B7B1;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">KAYIT OLUN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							<input type="email" name="email">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Kaydedin">
				   		</div>
					</form>
				</div>
				
				{{form.errors}}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Hesabın var mı? <a href="{% url 'user:login2' %}" class="ml-2">Giriş Yap</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Kullanıcı Adı..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Parola...';
		form_fields[4].placeholder='Parola Onay...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

templates/update.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %} <!--Crispy Formu dahil ettik-->

{% block body %}

<div class="container">
    <h1 class="display-3">Kayıt Güncelleyin</h1>
    <div class="row">
        <div style="margin: 30px; padding: 20px;"class="col-6 col-sm-3">
            <h3 class="">Güncelleyin</h3>
            <form method="post">
                {% csrf_token %}

                {{form|crispy}} <!--Formumuzu ekledik-->
                <hr>
                <button type="submit" class="btn btn-outline-danger btn-md">Oluştur</button>
            </form>
            
        </div>
    </div>
</div>

{% endblock body %}